{
 "title": "Klever Testnet",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Connected Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_connected_nodes{}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_mem_load_percent" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_cpu_load_percent" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "klv_cpu_load_percent" }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_epoch_number", "legendFormat": "Epoch" }
   ]
  },
  {
   "title": "Total Validator Made Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "klv_count_leader", "legendFormat": "Node Blocks" }
   ]
  },
  {
   "title": "Total Validator Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_live_validator_nodes" }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "klv_current_slot", "legendFormat": "Current Slot" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "klv_mem_load_percent" }
   ]
  },
  {
   "title": "TPS Peak",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_peak_tps" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_num_connected_peers", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Validator Accepted Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_count_consensus_accepted_blocks"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_num_validators" }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} transmit"
    }
   ]
  },
  {
   "title": "Slots Per Epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_slots_per_epoch" }
   ]
  },
  {
   "title": "Validator Signed Blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_consensus" }
   ]
  },
  {
   "title": "Transaction Pool Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "klv_tx_pool_load", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Network Sent (bps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "klv_network_sent_bps{}" }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} write"
    }
   ]
  },
  {
   "title": "Processor usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}