global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
      - targets: ['localhost:9093']

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'klever_metrics'
    static_configs:
      - targets: ['170.187.150.52:8080']
    metrics_path: "/node/metrics"

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['170.187.150.52:8081']
