global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus_klever'
    static_configs:
<<<<<<< HEAD
      - targets: ['yourIP:8080']
    metrics_path: "/node/metrics"

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['yourIP:8081']
=======
      - targets: ['ip_of_node:8080']
    metrics_path: "/node/metrics"

  # Example job for node_exporter
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100']

  # Example job for cadvisor
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
>>>>>>> parent of 3da22ee (Updated prometheus.yml to include cadvisor and alertmanager)
